insert into goal_and_player_scores_goals (Match_Number,Date_Year,Recorded_Time,Player_Name,Country_Code) values (1,2014,15,'Rivaldo','BR');
insert into goal_and_player_scores_goals (Match_Number,Date_Year,Recorded_Time,Player_Name,Country_Code) values (1,2014,75,'Willy Busch','DE');
insert into goal_and_player_scores_goals (Match_Number,Date_Year,Recorded_Time,Player_Name,Country_Code) values (1,2014,80,'Willy Busch','DE');
insert into goal_and_player_scores_goals (Match_Number,Date_Year,Recorded_Time,Player_Name,Country_Code) values (1,2014,95,'KarlHeinz Riedle','DE');
insert into goal_and_player_scores_goals (Match_Number,Date_Year,Recorded_Time,Player_Name,Country_Code) values (1,2014,115,'Maurizio Gaudino','DE');
insert into goal_and_player_scores_goals (Match_Number,Date_Year,Recorded_Time,Player_Name,Country_Code) values (2,2014,67,'Leandro Cufr','AR');
insert into goal_and_player_scores_goals (Match_Number,Date_Year,Recorded_Time,Player_Name,Country_Code) values (2,2014,114,'Leandro Cufr','AR');
insert into goal_and_player_scores_goals (Match_Number,Date_Year,Recorded_Time,Player_Name,Country_Code) values (2,2014,23,'Puck van Heel','NL');
insert into goal_and_player_scores_goals (Match_Number,Date_Year,Recorded_Time,Player_Name,Country_Code) values (3,2014,24,'Marinho Chagas','BR');
insert into goal_and_player_scores_goals (Match_Number,Date_Year,Recorded_Time,Player_Name,Country_Code) values (3,2014,76,'Marinho Chagas','BR');
insert into goal_and_player_scores_goals (Match_Number,Date_Year,Recorded_Time,Player_Name,Country_Code) values (3,2014,34,'Marinho Chagas','BR');
insert into goal_and_player_scores_goals (Match_Number,Date_Year,Recorded_Time,Player_Name,Country_Code) values (3,2014,90,'Oreco','BR');
insert into goal_and_player_scores_goals (Match_Number,Date_Year,Recorded_Time,Player_Name,Country_Code) values (3,2014,25,'Michael Reiziger','NL');
insert into goal_and_player_scores_goals (Match_Number,Date_Year,Recorded_Time,Player_Name,Country_Code) values (3,2014,95,'Willem van Hanegem','NL');
insert into goal_and_player_scores_goals (Match_Number,Date_Year,Recorded_Time,Player_Name,Country_Code) values (3,2014,111,'Puck van Heel','NL');
insert into goal_and_player_scores_goals (Match_Number,Date_Year,Recorded_Time,Player_Name,Country_Code) values (4,2014,123,'Juan Barbas','AR');
insert into goal_and_player_scores_goals (Match_Number,Date_Year,Recorded_Time,Player_Name,Country_Code) values (4,2014,124,'Jos Nehin','AR');
insert into goal_and_player_scores_goals (Match_Number,Date_Year,Recorded_Time,Player_Name,Country_Code) values (4,2014,125,'Leandro Cufr','AR');
insert into goal_and_player_scores_goals (Match_Number,Date_Year,Recorded_Time,Player_Name,Country_Code) values (4,2014,126,'Willy Busch','DE');
insert into goal_and_player_scores_goals (Match_Number,Date_Year,Recorded_Time,Player_Name,Country_Code) values (4,2014,127,'Willy Busch','DE');
insert into goal_and_player_scores_goals (Match_Number,Date_Year,Recorded_Time,Player_Name,Country_Code) values (4,2014,122,'Willy Busch','DE');
insert into goal_and_player_scores_goals (Match_Number,Date_Year,Recorded_Time,Player_Name,Country_Code) values (4,2014,128,'KarlHeinz Riedle','DE');
insert into goal_and_player_scores_goals (Match_Number,Date_Year,Recorded_Time,Player_Name,Country_Code) values (4,2014,129,'KarlHeinz Riedle','DE');
insert into goal_and_player_scores_goals (Match_Number,Date_Year,Recorded_Time,Player_Name,Country_Code) values (1,2010,67,'Rafael Martn Vzquez','ES');
insert into goal_and_player_scores_goals (Match_Number,Date_Year,Recorded_Time,Player_Name,Country_Code) values (2,2010,34,'Johnny Rep','NL');
insert into goal_and_player_scores_goals (Match_Number,Date_Year,Recorded_Time,Player_Name,Country_Code) values (2,2010,89,'Adrie van Kraay','NL');
insert into goal_and_player_scores_goals (Match_Number,Date_Year,Recorded_Time,Player_Name,Country_Code) values (3,2010,121,'Rivaldo','BR');
insert into goal_and_player_scores_goals (Match_Number,Date_Year,Recorded_Time,Player_Name,Country_Code) values (3,2010,122,'Rivaldo','BR');
insert into goal_and_player_scores_goals (Match_Number,Date_Year,Recorded_Time,Player_Name,Country_Code) values (3,2010,123,'Hilderaldo Bellini','BR');
insert into goal_and_player_scores_goals (Match_Number,Date_Year,Recorded_Time,Player_Name,Country_Code) values (3,2010,124,'Jnior Baiano','BR');
insert into goal_and_player_scores_goals (Match_Number,Date_Year,Recorded_Time,Player_Name,Country_Code) values (4,2010,12,'Pedro Uralde','ES');
insert into goal_and_player_scores_goals (Match_Number,Date_Year,Recorded_Time,Player_Name,Country_Code) values (4,2010,34,'Ivn Helguera','ES');
insert into goal_and_player_scores_goals (Match_Number,Date_Year,Recorded_Time,Player_Name,Country_Code) values (4,2010,67,'Ivn Helguera','ES');
insert into goal_and_player_scores_goals (Match_Number,Date_Year,Recorded_Time,Player_Name,Country_Code) values (4,2010,89,'Antonio Olmo','ES');
insert into goal_and_player_scores_goals (Match_Number,Date_Year,Recorded_Time,Player_Name,Country_Code) values (4,2010,95,'Johnny Rep','NL');
insert into goal_and_player_scores_goals (Match_Number,Date_Year,Recorded_Time,Player_Name,Country_Code) values (4,2010,112,'Eljero Elia','NL');