insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (1,2014,'BR',"Russinho");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (1,2014,'BR',"Rivaldo");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (1,2014,'BR',"Oreco");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (1,2014,'BR',"Batatais");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (1,2014,'BR',"Marinho Chagas");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (3,2014,'BR',"Russinho");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (3,2014,'BR',"Rivaldo");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (3,2014,'BR',"Oreco");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (3,2014,'BR',"Batatais");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (3,2014,'BR',"Marinho Chagas");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (2,2010,'BR',"Roberto");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (2,2010,'BR',"Jnior Baiano");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (2,2010,'BR',"Hilderaldo Bellini");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (2,2010,'BR',"Batatais");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (2,2010,'BR',"Rivaldo");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (3,2010,'BR',"Roberto");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (3,2010,'BR',"Jnior Baiano");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (3,2010,'BR',"Hilderaldo Bellini");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (3,2010,'BR',"Batatais");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (3,2010,'BR',"Rivaldo");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (1,2014,'DE',"Willy Busch");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (1,2014,'DE',"Bodo Illgner");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (1,2014,'DE',"Mario Gtze");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (1,2014,'DE',"KarlHeinz Riedle");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (1,2014,'DE',"Maurizio Gaudino");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (4,2014,'DE',"Willy Busch");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (4,2014,'DE',"Bodo Illgner");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (4,2014,'DE',"Mario Gtze");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (4,2014,'DE',"KarlHeinz Riedle");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (4,2014,'DE',"Maurizio Gaudino");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (1,2010,'ZA',"Themba Mnguni");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (1,2010,'ZA',"Surprise Moriri");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (1,2010,'ZA',"MacBeth Sibaya");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (1,2010,'ZA',"Brendan Augustine");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (1,2010,'ZA',"Moeneeb Josephs");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (3,2010,'ZA',"Themba Mnguni");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (3,2010,'ZA',"Surprise Moriri");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (3,2010,'ZA',"MacBeth Sibaya");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (3,2010,'ZA',"Brendan Augustine");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (3,2010,'ZA',"Moeneeb Josephs");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (1,2010,'ES',"Juan Acua");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (1,2010,'ES',"Rafael Martn Vzquez");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (1,2010,'ES',"Antonio Olmo");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (1,2010,'ES',"Ivn Helguera");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (1,2010,'ES',"Pedro Uralde");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (4,2010,'ES',"Juan Acua");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (4,2010,'ES',"Rafael Martn Vzquez");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (4,2010,'ES',"Antonio Olmo");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (4,2010,'ES',"Ivn Helguera");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (4,2010,'ES',"Pedro Uralde");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (2,2014,'NL',"Piet Keizer");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (2,2014,'NL',"Stanley Menzo");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (2,2014,'NL',"Puck van Heel");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (2,2014,'NL',"Michael Reiziger");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (2,2014,'NL',"Willem van Hanegem");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (3,2014,'NL',"Piet Keizer");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (3,2014,'NL',"Stanley Menzo");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (3,2014,'NL',"Puck van Heel");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (3,2014,'NL',"Michael Reiziger");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (3,2014,'NL',"Willem van Hanegem");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (2,2010,'NL',"Eljero Elia");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (2,2010,'NL',"Adrie van Kraay");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (2,2010,'NL',"Johnny Rep");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (2,2010,'NL',"Stanley Menzo");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (2,2010,'NL',"Willem van Hanegem");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (4,2010,'NL',"Eljero Elia");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (4,2010,'NL',"Adrie van Kraay");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (4,2010,'NL',"Johnny Rep");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (4,2010,'NL',"Stanley Menzo");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (4,2010,'NL',"Willem van Hanegem");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (2,2014,'AR',"Leandro Cufr");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (2,2014,'AR',"Jos Nehin");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (2,2014,'AR',"Norberto Boggio");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (2,2014,'AR',"Juan Barbas");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (2,2014,'AR',"ngel Grippa");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (4,2014,'AR',"Leandro Cufr");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (4,2014,'AR',"Jos Nehin");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (4,2014,'AR',"Norberto Boggio");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (4,2014,'AR',"Juan Barbas");
insert into match_played_by (Match_Number,Date_Year,Country_Code,Player_Name) values (4,2014,'AR',"ngel Grippa");