INSERT INTO world_cup_played_by_player (Year, Player_Name, Country_Code) VALUES (2014, "Russinho", "BR");
INSERT INTO world_cup_played_by_player (Year, Player_Name, Country_Code) VALUES (2014, "Rivaldo", "BR");
INSERT INTO world_cup_played_by_player (Year, Player_Name, Country_Code) VALUES (2014, "Oreco", "BR");
INSERT INTO world_cup_played_by_player (Year, Player_Name, Country_Code) VALUES (2014, "Batatais", "BR");
INSERT INTO world_cup_played_by_player (Year, Player_Name, Country_Code) VALUES (2014, "Marinho Chagas", "BR");
INSERT INTO world_cup_played_by_player (Year, Player_Name, Country_Code) VALUES (2010, "Roberto", "BR");
INSERT INTO world_cup_played_by_player (Year, Player_Name, Country_Code) VALUES (2010, "Jnior Baiano", "BR");
INSERT INTO world_cup_played_by_player (Year, Player_Name, Country_Code) VALUES (2010, "Hilderaldo Bellini", "BR");
INSERT INTO world_cup_played_by_player (Year, Player_Name, Country_Code) VALUES (2010, "Batatais", "BR");
INSERT INTO world_cup_played_by_player (Year, Player_Name, Country_Code) VALUES (2010, "Rivaldo", "BR");
INSERT INTO world_cup_played_by_player (Year, Player_Name, Country_Code) VALUES (2014, "Willy Busch", "DE");
INSERT INTO world_cup_played_by_player (Year, Player_Name, Country_Code) VALUES (2014, "Bodo Illgner", "DE");
INSERT INTO world_cup_played_by_player (Year, Player_Name, Country_Code) VALUES (2014, "Mario Gtze", "DE");
INSERT INTO world_cup_played_by_player (Year, Player_Name, Country_Code) VALUES (2014, "KarlHeinz Riedle", "DE");
INSERT INTO world_cup_played_by_player (Year, Player_Name, Country_Code) VALUES (2014, "Maurizio Gaudino", "DE");
INSERT INTO world_cup_played_by_player (Year, Player_Name, Country_Code) VALUES (2010, "Themba Mnguni", "ZA");
INSERT INTO world_cup_played_by_player (Year, Player_Name, Country_Code) VALUES (2010, "Surprise Moriri", "ZA");
INSERT INTO world_cup_played_by_player (Year, Player_Name, Country_Code) VALUES (2010, "MacBeth Sibaya", "ZA");
INSERT INTO world_cup_played_by_player (Year, Player_Name, Country_Code) VALUES (2010, "Brendan Augustine", "ZA");
INSERT INTO world_cup_played_by_player (Year, Player_Name, Country_Code) VALUES (2010, "Moeneeb Josephs", "ZA");
INSERT INTO world_cup_played_by_player (Year, Player_Name, Country_Code) VALUES (2010, "Juan Acua", "ES");
INSERT INTO world_cup_played_by_player (Year, Player_Name, Country_Code) VALUES (2010, "Rafael Martn Vzquez", "ES");
INSERT INTO world_cup_played_by_player (Year, Player_Name, Country_Code) VALUES (2010, "Antonio Olmo", "ES");
INSERT INTO world_cup_played_by_player (Year, Player_Name, Country_Code) VALUES (2010, "Ivn Helguera", "ES");
INSERT INTO world_cup_played_by_player (Year, Player_Name, Country_Code) VALUES (2010, "Pedro Uralde", "ES");
INSERT INTO world_cup_played_by_player (Year, Player_Name, Country_Code) VALUES (2014, "Piet Keizer", "NL");
INSERT INTO world_cup_played_by_player (Year, Player_Name, Country_Code) VALUES (2014, "Stanley Menzo", "NL");
INSERT INTO world_cup_played_by_player (Year, Player_Name, Country_Code) VALUES (2014, "Puck van Heel", "NL");
INSERT INTO world_cup_played_by_player (Year, Player_Name, Country_Code) VALUES (2014, "Michael Reiziger", "NL");
INSERT INTO world_cup_played_by_player (Year, Player_Name, Country_Code) VALUES (2014, "Willem van Hanegem", "NL");
INSERT INTO world_cup_played_by_player (Year, Player_Name, Country_Code) VALUES (2010, "Eljero Elia", "NL");
INSERT INTO world_cup_played_by_player (Year, Player_Name, Country_Code) VALUES (2010, "Adrie van Kraay", "NL");
INSERT INTO world_cup_played_by_player (Year, Player_Name, Country_Code) VALUES (2010, "Johnny Rep", "NL");
INSERT INTO world_cup_played_by_player (Year, Player_Name, Country_Code) VALUES (2010, "Stanley Menzo", "NL");
INSERT INTO world_cup_played_by_player (Year, Player_Name, Country_Code) VALUES (2010, "Willem van Hanegem", "NL");
INSERT INTO world_cup_played_by_player (Year, Player_Name, Country_Code) VALUES (2014, "Leandro Cufr", "AR");
INSERT INTO world_cup_played_by_player (Year, Player_Name, Country_Code) VALUES (2014, "Jos Nehin", "AR");
INSERT INTO world_cup_played_by_player (Year, Player_Name, Country_Code) VALUES (2014, "Norberto Boggio", "AR");
INSERT INTO world_cup_played_by_player (Year, Player_Name, Country_Code) VALUES (2014, "Juan Barbas", "AR");
INSERT INTO world_cup_played_by_player (Year, Player_Name, Country_Code) VALUES (2014, "ngel Grippa", "AR");